name: pogo
description: A 2D game engine for Flutter forked from Flame 0.18.1
version: 0.0.1
homepage: https://github.com/juanitogan/pogo

environment:
  sdk: ">=2.3.0 <3.0.0"
  #flutter: ">=1.6.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: '>=2.0.0 <3.0.0'
  audioplayers: ^0.14.0
  #ordered_set: ^1.1.5
  path_provider: ^1.6.0
  box2d_flame: ^0.4.5
  synchronized: ^2.1.0
  tiled: ^0.2.1
  convert: ^2.0.1
  flutter_svg: ^0.17.1
  flare_flutter: ^2.0.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  uses-material-design: false
