name: pogo
description: 2D game engine for Flutter. Implements a logical game-entity system for rapid development of simple games.
version: 0.2.0
homepage: https://github.com/juanitogan/pogo

environment:
  sdk: ">=2.3.0 <3.0.0"
  #flutter: ">=1.6.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: '>=2.0.0 <3.0.0'
  path_provider: ^1.6.6
  audioplayers: ^0.15.1
  synchronized: ^2.2.0  # used by audio
  flutter_svg: ^0.18.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  uses-material-design: false

#TODO look into "flutter: plugin: platforms: android: ..." requirements
