name: pogo
description: 2D game engine for Flutter. Implements a logical game-entity system for rapid development of simple games.
version: 0.1.2
homepage: https://github.com/juanitogan/pogo

environment:
  sdk: ">=2.3.0 <3.0.0"
  #flutter: ">=1.6.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: '>=2.0.0 <3.0.0'
  audioplayers: ^0.15.1
  path_provider: ^1.6.6
  box2d_flame: ^0.4.5
  synchronized: ^2.1.0
  tiled: ^0.2.1
  convert: ^2.0.1
  flutter_svg: ^0.17.4
  flare_flutter: ^2.0.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  uses-material-design: false
