name: flare
description: Flame sample for using Flare animations

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pogo:
      path: ../../../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/Bob_Minion.flr

