name: gestures
description: Example app showing the use of gesture mixins

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pogo:
      path: ../../../

flutter:
  uses-material-design: false
