name: widgets
description: Example project showing use of PogoWidget

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pogo:
      path: ../../../
  dashbook: ^0.0.2

  cupertino_icons: ^0.1.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/nine_tile_box.png
